### ISSUE TITLE
progn: Symbol's function definition is void: url-insert

### ISSUE THREAD

**Issue by alf** [ljos/sparql-mode#37]
This function is not available in my emacs (GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2014-10-21 on builder10-9.porkrind.org).

Am I missing a dependency from elpa?

**Comment by ljos** [comment]
I forgot to require `url-handlers`. I think it should have been fixed in b30305ed82d1b923d8c85bb358e068d22f26c5d8.

**Comment by ljos** [comment]
I seem to have been a bit hasty yesterday fixing some things and not testing properly. I think it should be OK now.

**Comment by alf** [comment]
Works again now. Thanks for the quick fix.
