### ISSUE TITLE
Add to ELPA

### ISSUE THREAD

**Issue by donpellegrino** [ljos/sparql-mode#39]
It would be great to include sparql-mode in the [Emacs Lisp Package Archive (ELPA)](http://emacswiki.org/emacs/ELPA) for ease of installation and upgrading.

**Comment by ljos** [comment]
It should already be on MELPA. I did use to update the marmelade one as well, but I don't think I have done that in a while. The process to get it on GNU ELPA is a bit involved and I don't have the energy to start that process right now. If someone else wants to contact the other contributors and get the ball rolling, I wouldn't mind. I have already signed the CA myself, but I don't know about the others.
