### ISSUE TITLE
"Cyclic keymap inheritance" error

### ISSUE THREAD

**Issue by cordawyn** [ljos/sparql-mode#46]
Using the latest version, `sparql-mode-20151102.149` from ELPA, I get "Cyclic keymap inheritance" error, when trying to run `sparql-query-region` (using a key combination or calling the function directly). And the query won't run.

(I use GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) on MacOSX).

**Comment by ljos** [comment]
I think it should be fixed now. thank you for reporting.
