### ISSUE TITLE
Hash in absolute URI causes code following close of URI to be treated as a comment

### ISSUE THREAD

**Issue by welchwilmerck** [ljos/sparql-mode#50]
In particular, breaks show-parens for matching {}

```
select *
where 
{
 graph ?g { <http://hashproblem#in-uri> ?p ?o . }
}
```

**Comment by ljos** [comment]
I want to fix this, but I'm not sure we can with the current regexp based approach using font-lock-mode. I will have to look into it, or I can hope you or someone else has an idea for how to do it without writing a lot of new code?

**Comment by ljos** [comment]
I have identified the solution. I think by treating <> as a parenthesis pair in the syntax-table and taking into account the context we are fontifying in we should be able to fix this problem. It should also make the fontification more robust and easier to fix problems we discover in the future.

It is going to take a couple of days before I can attempt a solution though.

**Comment by ljos** [comment]
I found a temporary solution. I need to understand syntax tables and fontification better before I can attempt a proper solution.
