### ISSUE TITLE
Company integration problems

### ISSUE THREAD

**Issue by TheBB** [ljos/sparql-mode#52]
https://github.com/ljos/sparql-mode/blob/master/sparql-mode.el#L356-L359

First of all, `company-keywords-alist` is defined in `company-keywords.el`, not `company.el`, therefore it's not guaranteed to be defined even if `company-mode` is bound.

Second, I believe the appropriate way to do this is to modify the default value of `company-backends` *once*, not set it every time your mode loads.

Third, `company-keywords-alist` should also only be modified *once*. I don't need 20 entries for `sparql-mode` in there if I open 20 `sparql-mode` buffers.

**Comment by TheBB** [comment]
None of the other custom company backends I have seen modify `company-backends` on their own, by the way. It seems this is usually considered to be in the user configuration domain.

**Comment by ljos** [comment]
Hi TheBB,

You don't get 20 entries in `company-keywords-alist`. The documentation for `add-to-list` says

> This function sets the variable symbol by consing element onto the old value, if element is
> not already a member of that value.

It uses `equal` as the comparison function for doing that. I tested now and it looks like it does the comparison correctly and `sparql-mode` is only added once, even if the `add-to-list` section is ran multiple times.

If I remember correctly, the way I implemented this was that I just looked up some random mode and copied that to get a backend that worked. I would appreciate it if you could tell me if you know what the best practice is in this instance. I couldn't figure it out from reading the documentation for `company-mode`. The reason for doing it this way was to be as convenient for `company-mode` users as possible, but if this is getting in the way of how other modes are interacting with `company-mode` I will of course change it.

**Comment by TheBB** [comment]
Okay, sorry about that. I misremembered the behaviour of `add-to-list`.

I can prepare a PR with how I think it should be done.

**Comment by ljos** [comment]
If you can do that I would appreciate it.

**Comment by TheBB** [comment]
See if https://github.com/ljos/sparql-mode/pull/53 is agreeable.

**Comment by ljos** [comment]
That looks great! It really makes sense to do it like that. I'll merge it
when I get back to the office later tonight or tomorrow. Thanks!
