### ISSUE TITLE
Evaluation of SPARQL in Org is disabled

### ISSUE THREAD

**Issue by wouterbeek** [ljos/sparql-mode#55]
When I press `C-c C-c` on a SPARQL code block inside Org mode, I get the following message: "Evaluation of this SPARQL code block is disabled."

This is how I markup the query in Org:

```org
#+BEGIN_SRC sparql :url http://localhost:3020/sparql :format test/csv
select * { ?s ?p ?o } limit 1
#+END_SRC
```

The same query does work when `M-x  sparql-query-region` is performed in a SPARQL buffer.

`emacs-version` is 26.0.50; `org-version` is 9.0.5.

**Comment by ljos** [comment]
You have written `test/csv` instead `text/csv` and I had made a mistake handling error responses. I fixed the error and now you should get better error messages when the server gives an error response.

**Comment by wouterbeek** [comment]
@ljos Thanks for the quick response!  I've fixed my typo, but am still receiving the same message.

**Comment by ljos** [comment]
I looked up the error; seems to be a change in org mode 9. Try to recompile
the byte code for org mode and ob-sparql. You might also need to add sparql
to the org-babel-do-load-languages.
