### ISSUE TITLE
Unable to run SPARQL query from within an Org file

### ISSUE THREAD

**Issue by wouterbeek** [ljos/sparql-mode#57]
I have the following content in an Org file:

```org
#+BEGIN_SRC sparql
select ?s ?p ?o {
  ?s ?p ?o
}
limit 1
#+END_SRC
```

Pressing `C-c C-c` while point is within this code block gives the following response:

```
Trying to parse HTTP response code in odd buffer: *http localhost:2020*-159759
```

I do not know what message means (e.g., what is an off buffer?).  There does not seem to be a buffer with the given `*http ...` name.

My OS is Fedora 25, `M-x emacs-version` is 25.2.1, and `M-x org-version` is 9.0.8.

The relevant part in my `.emacs/init.el` is:

```elisp
;; SPARQL
(add-to-list 'load-path "/path/to/sparql-mode-dir")
(autoload 'sparql-mode "sparql-mode.el"
    "Major mode for editing SPARQL files" t)
(add-to-list 'auto-mode-alist '("\\.sparql$" . sparql-mode))
(add-to-list 'auto-mode-alist '("\\.rq$" . sparql-mode))

;; Org Babel
(org-babel-do-load-languages
 'org-babel-load-languages
 '((sparql . t)))
```

**Comment by ljos** [comment]
It did work as it was, it was just giving a bad error message. The problem was that you have no sparql endpoint at `http://localhost:2020/`. It should now give a better error message in this case.
