### ISSUE TITLE
Mode is not blank nodes indentation aware

### ISSUE THREAD

**Issue by jgrzebyta** [ljos/sparql-mode#60]
Neither TAB command nor autoindentation after pressing RET is not indention aware after I use blank nodes in SPARQL.

Code:
```
  raw:hasReading [
                             rdf:rest*/rdf:first [
                                                       raw:unit ?unit ;
                                                       rdf:value ?value ;
                                                       ] ;
                             ] .
```
Is just converted to:

```
  raw:hasReading [
  rdf:rest*/rdf:first [
  raw:unit ?unit ;
  rdf:value ?value ;
  ] ;
  ] .
```
I attached file with expected indentation. After pressing <TAB> it is simply destroyed.

[example-sparql.txt](https://github.com/ljos/sparql-mode/files/1180597/example-sparql.txt)

**Comment by ljos** [comment]
Thank you for reporting. I will fix this as soon as I can.

**Comment by ljos** [comment]
It should now be fixed. Please test and report any errors you find.

**Comment by jgrzebyta** [comment]
@ljos Works very well. 
Also it is possible to customize indention size. What is brilliant! Thanks very much..
