### ISSUE TITLE
sparql-indent-offset variable does not affects blank nodes indention

### ISSUE THREAD

**Issue by jgrzebyta** [ljos/sparql-mode#61]
Ref #60 

I found when I change `sparql-indent-offset` it does not affect indention within blank nodes. By default it always stay 2. 

It would be great if blank nodes indention value would be negative. Maybe it is worth to create variable `sparql-bnode-indent-offset`.

**Comment by ljos** [comment]
What do you mean by the indentation value being negative? Can you show me an example?

**Comment by ljos** [comment]
I pushed a patch for the first part; the indentation of blank nodes is always 2.

**Comment by jgrzebyta** [comment]
File with example of the negative indention is attached with exmaple indent value **-4**. It is simply 4 spaces to the left from the nearest open bracket ([) column.

[negative-indent.txt](https://github.com/ljos/sparql-mode/files/1267077/negative-indent.txt)

**Comment by ljos** [comment]
Is this desirable? The way it is implemented now (especially with the latest patch) is the way that the specification formats blank nodes. I could see an argument for indenting blank nodes the same way as other parenthesis, so

```sparql
select * where {
  ?row raw:hasParameterX ?param1 ;
  raw:hasParameterY ?param2 ;
  raw:hasReading [
    rdf:rest*/rdf:first [
      raw:unit ?unit ;
      rdf:value ?value ;
    ] ;
  ] .
}

```

Which would mean we just indent in according to previous indentation column instead the special case of blank nodes where the indentation is based on the column of the previous `[`. This could be configurable, but a negative indentation based on the column of `[` feels strange to me.

**Comment by jgrzebyta** [comment]
@ljos No I do not have any special reason to have negative indentation. It seems your argumentation is correct: indentation should be based on the previous bracket not the current one.
