### ISSUE TITLE
Feature: Specify base url in -*- inline

### ISSUE THREAD

**Issue by metawilm** [ljos/sparql-mode#62]
It would be practical if the SPARQL endpoint could be configured at the top of the file, like: 
`-*- mode: sparql; sparql-base-url: http://live.dbpedia.org/sparql -*-`

**Comment by ljos** [comment]
If you put that in a comment as the first line of the file it should work as you expect. Thank you for suggesting improvements to SPARQL mode though.

**Comment by metawilm** [comment]
It seems that is not the case, unless I'm misunderstanding.
Loading this file:
```
# -*- mode: sparql; sparql-base-url: http://live.dbpedia.org:80/sparql -*-

SELECT * WHERE {
  ?sub ?pred ?obj .
} LIMIT 10
```
does warn about setting the local variable (which I allow) of
```* sparql-base-url : http://live\.dbpedia\.org:80/sparql ```

But then running `C-c C-c` on the query does not take into account the local variable url, as it suggests:
```SPARQL URL (http://localhost:2020/):```
even though eval-expression (`M-:`) of `sparql-base-url` does return the dbpedia url.

**Comment by ljos** [comment]
Oh, yeah. I see. I tested it, but I have set dbpedia as my default so it looked like it changed to me. I will have a look at a fix.

**Comment by ljos** [comment]
I think it should work now.

**Comment by metawilm** [comment]
I get `url-retrieve-internal: Wrong type argument: char-or-string-p, http://live\.dbpedia\.org:80/sparql`

**Comment by ljos** [comment]
Oh, you need "" around the link like

`# -*- mode: sparql; sparql-base-url: "http://live.dbpedia.org/sparql" -*-`

**Comment by metawilm** [comment]
Thanks, great!
