### ISSUE TITLE
Support for Emacs 24.3.1

### ISSUE THREAD

**Issue by donpellegrino** [ljos/sparql-mode#63]
It would be a great enhancement if sparql-mode could support the older Emacs 24.3.1 release. This is the current Emacs release packaged by Red Hat and CentOS. It looks like it might be a while before those distributions get Emacs 25.

**Comment by ljos** [comment]
Fixed in 54b43521e50bf7bdc122c5942a0be6d054931919. 

It seems like the only thing I used in 25 was `with-eval-after-load` and in this case I don't think I should do that so I removed it.

Thank you for reporting the issue.

**Comment by donpellegrino** [comment]
Thanks for the commit! This is much more convenient for working on Red Hat and CentOS systems. I installed sparql-mode with the Emacs package manager. It reports version 20180320.757 with Emacs version 24.3.1. The installation reporting the following messages, but it appears to be working. I was able to enable sparql-mode and it handled the syntax highlighting for a sparql buffer beautifully.

```
Leaving directory `/home/user/.emacs.d/elpa/sparql-mode-20180320.757'

Compiling file /home/user/.emacs.d/elpa/sparql-mode-20180320.757/company-sparql.el at Tue Mar 20 13:34:35 2018
Entering directory `/home/user/.emacs.d/elpa/sparql-mode-20180320.757/'
company-sparql.el:37:1:Error: Symbol's function definition is void: function-put

Compiling file /home/user/.emacs.d/elpa/sparql-mode-20180320.757/ob-sparql.el at Tue Mar 20 13:34:35 2018

In end of data:
ob-sparql.el:92:1:Warning: the following functions are not known to be defined:
    org-babel-result-cond, org-babel--get-vars

Compiling file /home/pellegrinoda/.emacs.d/elpa/sparql-mode-20180320.757/sparql-mode.el at Tue Mar 20 13:34:35 2018

In end of data:
sparql-mode.el:346:1:Warning: the function `save-mark-and-excursion' is not
    known to be defined.
```

**Comment by ljos** [comment]
I have added some requires for the package and removed the use of save-mark-and-excursion. I think it should work now when melpa updates.

Or, I don't really know how melpa handles the package requires stuff in different files. sparql-mode proper should work anyway though.
