### ISSUE TITLE
Trailing `=` added to var name

### ISSUE THREAD

**Issue by VladimirAlexiev** [ljos/sparql-mode#64]
When writing eg
```sparql
?filmingLocation rdfs:label ?locationNameEn 
filter(lang(?locationNameEn="en"))
bind(str(?locationNameEn) as ?locationName)
```
it offers `?locationNameEn=` as possible var name completion

**Comment by ljos** [comment]
Which completion engine do you use?

**Comment by ljos** [comment]
Thank you for reporting the issue.  I think it should be fixed in master now.
