### ISSUE TITLE
DBpedia doesn't support text/csv anymore?

### ISSUE THREAD

**Issue by Alf0nso** [ljos/sparql-mode#66]
I was going to get some info directly into a project I was playing around with, and well I got this error.
I first thought it could be something I had written wrongly, but even the most basic sparql query results in an error

![Captura de ecrã 2021-01-22 123219](https://user-images.githubusercontent.com/32681068/105491397-2208d080-5cae-11eb-8218-4f889be002f8.png)

From the error they give I believe text/csv is no longer supported?
I am not able to extract info this way in any other format as well...

![Captura de ecrã 2021-01-22 123338](https://user-images.githubusercontent.com/32681068/105492323-af98f000-5caf-11eb-808a-27583bb32335.png)

**Comment by justin2004** [comment]
this returns text/csv

```
 curl 'https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org'  -H 'Accept: text/csv' -H --compressed -H 'Connection: keep-alive' -H 'Referer: https://dbpedia.org/sparql/' -H 'Upgrade-Insecure-Requests: 1' --data-urlencode query="select * where {?s ?p ?o} limit 3"
 ```

**Comment by Alf0nso** [comment]
Maybe it's my version of curl?
(curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL)

![image](https://user-images.githubusercontent.com/32681068/105912078-d7c37e80-6022-11eb-899f-151afeac1008.png)

This what I get when I use your command without emacs...
with emacs it keeps getting that bad result

**Comment by justin2004** [comment]
@Alf0nso what shell did you run that curl command in?
i used bash.

**Comment by Alf0nso** [comment]
I am running over on cmd.exe, windows!
I should probably try to see if there isn't any new more updated version, or do you think the problem might be another?

**Comment by justin2004** [comment]
i think your curl command might not accept -H options (headers). 

can you try `curl /?`
or `curl --help` to see if it accepts -H as an option

**Comment by Alf0nso** [comment]
Here:

![image](https://user-images.githubusercontent.com/32681068/105919534-b6b45b00-602d-11eb-8704-610946bb180e.png)

it does refer the header option!

**Comment by justin2004** [comment]
see where your output says:
"could not resolve host text"

i think that means your curl is ignoring the 'Accept: text/csv' header which is what is giving me csv.

does cmd.exe not protect text in single quotes?

**Comment by Alf0nso** [comment]
![image](https://user-images.githubusercontent.com/32681068/105921884-6b9c4700-6031-11eb-8a96-8fe57591548f.png)

It does look like the problem was the use of \' instead of \"
but now how would I go on to make it work on emacs again?... (yes it did previously work, proof: [stackoverflow answer I gave](https://stackoverflow.com/questions/23086995/setting-correct-endpoints-for-dbpedia-in-emacs-sparql/64917974#64917974))

**Comment by justin2004** [comment]
can you turn on emacs debug messages so you can see the REST call it makes?

oh and it might be that you didn't use https in you endpoint?

**Comment by Alf0nso** [comment]
I hope I don't get judge, but yes... my problem was that I was using http instead of https... Thank you for your time... and sorry that I wasted it with such a small distraction of mine...

![image](https://user-images.githubusercontent.com/32681068/105984652-5a375700-6092-11eb-8e7e-bf860208f5c3.png)

**Comment by ljos** [comment]
@Alf0nso We all make these mistakes at times, so don't worry about it. I am sorry I wasn't able to help with this issue.

@justin2004 I appreciate you helping out. Thank you!

**Comment by Alf0nso** [comment]
Don't apologize! everyone has their schedules and things they have to do :)
